<a href="https://colab.research.google.com/github/Pardhu156/Power-Output-Prediction/blob/main/Power_Production.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.18.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset=pd.read_excel('Folds5x2_pp.xlsx')
X=dataset.iloc[ : , :-1].values
y=dataset.iloc[ : , -1].values

In [ ]:
y=y.reshape(len(y),1)

.reshaped for feature scaling

In [ ]:
print(y)

[[463.26]
 [444.37]
 [488.56]
 ...
 [429.57]
 [435.74]
 [453.28]]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
print(y_train)

[[473.93]
 [467.87]
 [431.97]
 ...
 [459.01]
 [462.72]
 [428.12]]


###Feature Scaling


In [ ]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
sc_y=StandardScaler()
X_train=sc_x.fit_transform(X_train)
X_test=sc_x.transform(X_test)
y_train=sc_y.fit_transform(y_train)
y_test=sc_y.transform(y_test)

In [ ]:
print(X_train)

[[-1.13572795 -0.88685592  0.67357894  0.52070558]
 [-0.80630243 -0.00971567  0.45145467  0.14531044]
 [ 1.77128416  1.84743445  0.24279248 -1.88374143]
 ...
 [-0.38409993 -1.24886277  0.84522042  0.13092486]
 [-0.9232821  -1.04155299  1.54693117  0.8830852 ]
 [ 1.70136528  1.05824381 -1.20438076 -2.42285818]]


In [ ]:
print(y_train)

[[ 1.15069786]
 [ 0.79540777]
 [-1.30936356]
 ...
 [ 0.27595724]
 [ 0.49346982]
 [-1.53508417]]


## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann=tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the third hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer='adam',loss='mean_squared_error')

### Training the ANN model on the Training set

In [ ]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 0.7934
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.1265
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.0977
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0792
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0714
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0681
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0632
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0618
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0644
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0649
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0621
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0632
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0628
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0653
Epoch 15/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1

### Predicting the results of the Test set

In [ ]:
y_train=sc_y.inverse_transform(y_train)
y_test=sc_y.inverse_transform(y_test)

In [ ]:
y_pred=sc_y.inverse_transform(ann.predict(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_pred),1)),1))

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[435.21 431.23]
 [458.59 460.01]
 [463.56 461.14]
 ...
 [469.44 473.26]
 [438.55 438.  ]
 [460.61 463.28]]


##Predict


In [ ]:
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred))

0.9452488041532403
